exports.genreIds = {
  Action: 1,
  Adventure: 2,
  Cars: 3,
  Comedy: 4,
  "Avant Garde": 5,
  Demons: 6,
  Drama: 8,
  Ecchi: 9,
  Fantasy: 10,
  Game: 11,
  Harem: 35,
  Hentai: 12,
  Historical: 13,
  Horror: 14,
  Josei: 43,
  Kids: 15,
  "Martial Arts": 17,
  Mecha: 18,
  Military: 38,
  Music: 19,
  Mystery: 7,
  Parody: 20,
  Police: 39,
  Psychological: 40,
  Romance: 22,
  Samurai: 21,
  School: 23,
  "Sci-Fi": 24,
  Seinen: 42,
  Shoujo: 25,
  Shonen: 27,
  "Slice of Life": 36,
  Space: 29,
  Sports: 30,
  "Super Power": 31,
  Supernatural: 37,
  Vampire: 32,
};

exports.pagesPerGenre = {
  Action: 40,
  Adventure: 32,
  Cars: 2,
  Comedy: 64,
  "Avant Garde": 6,
  Demons: 6,
  Drama: 28,
  Ecchi: 8,
  Fantasy: 36,
  Game: 5,
  Harem: 5,
  Hentai: 14,
  Historical: 13,
  Horror: 5,
  Josei: 1,
  Kids: 35,
  "Martial Arts": 5,
  Mecha: 12,
  Military: 6,
  Music: 25,
  Mystery: 8,
  Parody: 7,
  Police: 3,
  Psychological: 4,
  Romance: 20,
  Samurai: 3,
  School: 18,
  "Sci-Fi": 27,
  Seinen: 9,
  Shoujo: 7,
  Shonen: 20,
  "Slice of Life": 21,
  Space: 6,
  Sports: 8,
  "Super Power": 7,
  Supernatural: 26,
  Vampire: 2,
};

exports.endpoints = {
  watching: {
    get: "http://localhost:5000/watching&page=",
    delete: "http://localhost:5000/watching/",
    any: "http://localhost:5000/watching",
  },
  plantowatch: {
    get: "http://localhost:5000/plan&page=",
    delete: "http://localhost:5000/plan/",
    any: "http://localhost:5000/plan",
  },
  stat: "http://localhost:5000/stats&year=",
  rating: {
    get: "http://localhost:5000/rating&page=",
    any: "http://localhost:5000/rating",
    deletepatch: "http://localhost:5000/rating/",
    share: "http://localhost:5000/share",
    shared: "http://localhost:5000/shared/",
  },
  auth: {
    postSignup: "http://localhost:5000/signup",
    postLogin: "http://localhost:5000/login",
    postRecovery: "http://localhost:5000/recovery",
    patchReset: "http://localhost:5000/reset/",
  },
};
